// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEcjYqunb8cTMIZgKzHQk0pFwYFaJ3dZM',
    appId: '1:994114394192:web:00bc9571bc55e1ed8d5955',
    messagingSenderId: '994114394192',
    projectId: 'fir-flutter-codelab-a1ec6',
    authDomain: 'fir-flutter-codelab-a1ec6.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a1ec6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzl5eo4qR1xvY5M2q3RfZSUAnVzkZB4k',
    appId: '1:994114394192:android:7cbc82e81f2b7b6e8d5955',
    messagingSenderId: '994114394192',
    projectId: 'fir-flutter-codelab-a1ec6',
    storageBucket: 'fir-flutter-codelab-a1ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9aaXxtIgKDSnMGbzIKkQyL8vhhRGQd8',
    appId: '1:994114394192:ios:af94084afc0a8b718d5955',
    messagingSenderId: '994114394192',
    projectId: 'fir-flutter-codelab-a1ec6',
    storageBucket: 'fir-flutter-codelab-a1ec6.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw9aaXxtIgKDSnMGbzIKkQyL8vhhRGQd8',
    appId: '1:994114394192:ios:af94084afc0a8b718d5955',
    messagingSenderId: '994114394192',
    projectId: 'fir-flutter-codelab-a1ec6',
    storageBucket: 'fir-flutter-codelab-a1ec6.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
